{% set name = "asammdf" %}
{% set version = "7.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9246bcd9eafbee26468fd8a7fcdb5e2cf053bdca4fa8520ffbf6b0b21591ef3b

build:
  number: 0
  skip: True # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vvv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - numpy {{ numpy }}
  run:
    - python
    - numpy >=1.23
    - numexpr
    - wheel
    - pandas
    - canmatrix >=0.8
    - natsort
    - lxml
    - lz4
    - python-dateutil
    - typing_extensions 
    #optional dependencies
    - matplotlib-base  #fallback for Signal plotting
    - cchardet #to detect non-standard Unicode encodings
    - chardet #to detect non-standard Unicode encodings
    - python-isal # [x86_64] for faster zlib compression/decompression

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - asammdf

about:
  home: https://github.com/danielhrisca/asammdf
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: ASAM MDF measurement data file parser
  description: |
    *asammdf* is a fast parser/editor for ASAM (Associtation for Standardisation of Automation and Measuring Systems) MDF (Measurement Data Format) files. \n\n*asammdf* supports MDF versions\
    \ 2 (.dat), 3 (.mdf) and 4 (.mf4). \n\n*asammdf* works on Python >= 3.8\
    GUI available that is based on pyqtgraph and PySide6
  doc_url: https://asammdf.readthedocs.io/en/master/
  dev_url: https://github.com/danielhrisca/asammdf

extra:
  recipe-maintainers:
    - danielhrisca
