travis:
  secure:
    BINSTAR_TOKEN: lGsQcwQJlYXs5ApjvCOhliCIvqaLIUUCpyH95vxG1SwuNeGD5vuOhF+7eGcHYdyc+zZ4to2E0NxyVcGmcGz8oxmCkDC+tH3TjMiInj6iuXh0V2u1BAspAUueo2Y2x5VZ6U5UF/JkdLTYHTN35ID+hoV25Z6My7oWzJgT0LlJO2x+8IthV/BDrMEBptwDE3aV1hJR9Pqc7fwARm2JUETc5/PJxPQrxpWhyREeIi7Q9m2Kh606r40atR7Ezey7kTXrOvgx4iG74adniLPj7LlxevS6WjoXW3l9A4eu/HabGadZ37guKJpjuzf+WN0TgzzCDaRWqgB3z80cANZDUafYw+7euDZgiwVqKnLVH13AiUgmPXMcVdUI1CBgPLbN/mGdL3ndIGRSyUVJAU/IqXXkE01ahMJVDvTSldQ2xZd/2S6EebRETwkY5WdEuIg9MIVKnNfKbvtjSUpvkUvWrD0tZtgZJ2G7Yqx3fieluhXBazGjOJbbElkC1TrEmR+7iEeaEX0ApMZO6DlU6FXGr8Xn3cjcDrVDtLCR2T6IZChu4Aa5xEy20j4dm3THTnnxUQd9RFB6XsOUyfYTDT4gkKg4NkqJzoWkgEnmBGwadrGGx8njNZiI+AFShQveFkOTm5UttWbiU0Rcac0LWfoaCBt0OaiLjozUFh45SGpNK2b/nzQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
