travis:
  secure:
    BINSTAR_TOKEN: QUiYm9pu4RPmkd8yY7P2vx2ftBD6+bYQIPvhlYLUxkZuaJtOoYW1eDMpn4V0T7tencvNmxAwC8tPLOL6TSM6zlxk2GJCvOn8aeTBflL+MqflwvczFwPv9sKdAeob6LmivftXnP/dTx4ajnjzbNr8kqLItWUBf1fRnUSF4n8fvCAwMhlTkycBamMvkYxOR0RV+Eb4kGOi7hBq1EJKfkAtc+HW1RXcbCyYcK3I4QMgNAWdmP1uAZdMKZ0tnjYtTuHpuq5doSw3DMZlohmyENJrS4016Q/sW8BZK+CXYEAeY+g7BnvN7ufMZ+aRtGwqeWahRyMKC9qdEsqWjLfFnmAtgJohFrDuoAaLaohPmF0CgnHIQGIhYXM0UEpFbIzzhmIA6T8qmVtoD8P/hI7Dtoxi4BSvpcsOdnYe+OBFrejvZQnpu7YJb/x+8w7mil7MN1/1HZ6tjtWN2cS/d3vaTtVz0Gs+Vqw0xxpkeVhz1+8k3a0uv1llqVNOrZrIgfWY5t8gnoPwKlcspat7u4+PAC7q6fFIL4ymijq5vIR67Xha1R7y8JdH7DmOR4dP2P7kyYt5cvBBa6ufqttOa7GNHBJSNEdPsgDyxWPW/CSf72X8PLj+0P5OG14MDT9qXI4JUPqO8P/BY3bQnuageEqCv5sAwm27uirdrWIcTD8t4yfv7/c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
